name: Build and Deploy to GitHub Pages

on:
  # Runs when pull request gets closed on merge
  pull_request:
    types:
      - closed
    branches: 
      - $default-branch

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install node
    - uses: actions/setup-node@v1

    - name: Build code
      run: |
        npm install
        npm run build
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v4
      env:
        ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build