# Setting up unit-testing workflow
name: Unit Testing Workflow

on:
  push

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v1
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Run unit-test
        run: npm run unit-test